### ISSUE TITLE
eval() support

### ISSUE THREAD

**Issue by jorge-matricali** [jorge-matricali/x3n4#20]

**Comment by davidtavarez** [comment]
Because most of the hosting servers tend to block `eval()` I will add something like this https://gonzalo123.com/2012/03/12/how-to-use-eval-without-using-eval-in-php/

**Comment by davidtavarez** [comment]
Is there any comment on this PR https://github.com/jorge-matricali/x3n4/pull/21 ?

**Comment by matricali** [comment]
@davidtavarez : It's OK
